---
abstract: 'N-Gram Alrogithm for Unicode String'
author:
  - 'Gea-Suan Lin <gslin@gslin.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-Gram
provides:
  Lingua::Gram:
    file: lib/Lingua/Gram.pm
    version: 0.01
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
